### ISSUE TITLE
log scale on y axis in plotLextreme

### ISSUE THREAD

**Issue by Irfan9948** [brry/extremeStat#1]
I plot the return periods graphs with 17 distribution. The only issue is, i want log scale on y axis. As in code only "log=TRUR" which shows log scale on x axis. But i want log scale on y axis also. 
As the peak values of different station are too vary.

**Comment by brry** [comment]
This is doable, will work on it next week after vacation :)

**Comment by Irfan9948** [comment]
Thank you Sir, Enjoy your vacation, we will discuss the issue next week. Below is the code which is run correctly, but the only problem is i want log scale on y axis also. suggest me any correction that i replace the "log=TRUE", because by default this log is on x axis.  
bara_kohat=distLextreme(discharge,quiet = TRUE)
> plotLextreme(bara_kohat,main="Bara_River_Kohat Return Period",xlab="Return Period(Yrs)",ylab="Peak Discharge (ft3/sec)",log=TRUE, legargs = list(cex=0.6,bg="transparent"),nbest = 17)
> bara_kohat$returnlev[1:20,]
plotLextreme(dlf,log = TRUE,main = "Bara River at Tarnab (RP)", xlab = "Retrun Period(Yrs)", ylab = "Peak Discharge (ft3/sec)", nbest=17,legargs = list(cex=0.4, bg="transparent"))

**Comment by brry** [comment]
I just updated the code to enable `plotLextreme(dlf, log="xy")`, see https://github.com/brry/extremeStat/commit/6ec0272  
Could you check if everything works as you would like it to?

You can update with   
`remotes::install_github("brry/extremeStat")`   
and should then have `packageVersion("extremeStat")` 1.4.4 (2020-08-17)

**Comment by Irfan9948** [comment]
Thank you very much sir, its working. I got both the axis with log scale...
Thank you once again for giving me your precious time.

**Comment by brry** [comment]
you're welcome :)
