### ISSUE TITLE
bootstrapping sampling technique

### ISSUE THREAD

**Issue by K-Asta** [brry/extremeStat#2]
Calculating confidence intervalls of return periods using extremeStat::distLexBoot I stumbled across the bootstrapping sampling. 
I assumed bootstrapping samples are taken with replacement, eg. (sample(x, size, replace = TRUE)). 
Currently sampling is done without replacement, is this on intend?

**Comment by brry** [comment]
Thanks for bringing this up. I've never really thought about it. I just went with the `sample` default. 

I've now added an argument `replace` to control this. The default is FALSE for backwards compatibility.
The argument is available with the latest version 1.4.5:

```r
remotes::install_github("brry/extremeStat", build_vignettes=TRUE)
```
