### ISSUE TITLE
Statistical Distributions names  

### ISSUE THREAD

**Issue by Irfan9948** [brry/extremeStat#3]
Dear Sir, 
I am using your extremeStat package for the prediction of different Rivers using the available 17 different statistical distribution, which is mentioned in this package (extremeStat). it is a kind request that please provide the full names of each distribution, as the distributions are in the short form (i.e. wak, gev, nor, lap, etc). I googled most of them for the full name but some were found for more than one distribution. 

Best Regards 
Muhammad Irfan

**Comment by brry** [comment]
https://rdrr.io/cran/lmomco/man/prettydist.html

**Comment by Irfan9948** [comment]
Thank you so much.
