### ISSUE TITLE
is there a way to make sure the fitted curve go through the max observation data?

### ISSUE THREAD

**Issue by JTang-qhzx** [brry/extremeStat#5]
Hi,would you please help me with the problem that when fitting GEV distribution to some kind of  block maxima rainfall data?The question is that" **how to make sure the fitted curve go through the max observation rainfalldata using extremeStat**?",many thanks!

**Comment by brry** [comment]
See the [vignette](https://cran.r-project.org/web/packages/extremeStat/vignettes/extremeStat.html) and the GOF measures mentioned there.
